<style>body{margin:0;padding:0;}</style>
<meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />

<div style="background-color: #fefefe; padding: 35px 10px; box-sizing: border-box;">
    <h1 style="text-align: center; margin: 0; padding: 0; line-height: 32px;">Hi {NAME},<br/>vielen Dank für Deine<br/>Registrierung!</h1>
    <p style="font-size: 16px; margin-top: 40px;">Dein Verifizierungscode lautet:</p>
    <h2 style="text-align: center;">{CODE}</h2>
    <br>
    <p style="font-size: 16px;">Viele Grüße</p>
    <p style="font-size: 16px;">Dein Chefkoch Team</p>
</div>